### ISSUE TITLE
Testing out Cookbook install instructions from using a new OSX user

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy-Cookbook#15]
The link to standalone programs is good. Add links for pip and developer installs to section 1.2 "Full PmagPy install"  Maybe change title to 1.2 "Pip/Developer install"

Changed some wording on the OSX pip install page.

Got "twisted 18.7.0 requires PyHamcrest>=1.9.0, which is not installed." in red when installing wxPython. As I got a different error/warning message before but everything worked, maybe a notice saying "Do worry if you get some warnings in red. Just continue"

(base) kamacite:~ test2$ pip install --upgrade -f https://wxpython.org/Phoenix/snapshot-builds/ wxPython
Looking in links: https://wxpython.org/Phoenix/snapshot-builds/
Collecting wxPython
  Downloading https://files.pythonhosted.org/packages/1f/12/8b2558a4dd89afa22e31eb01ddea231f2239e0f3ca5dbbbf0c06d296df26/wxPython-4.0.3-cp37-cp37m-macosx_10_9_x86_64.whl (31.2MB)
    100% |████████████████████████████████| 31.2MB 903kB/s 
Collecting PyPubSub (from wxPython)
  Downloading https://files.pythonhosted.org/packages/ab/9e/3b50915d3346971aaa49074425788598ee4907e67c097e013f1a862bd45c/Pypubsub-4.0.0-py3-none-any.whl (63kB)
    100% |████████████████████████████████| 71kB 4.1MB/s 
Requirement not upgraded as not directly required: six in ./anaconda3/lib/python3.7/site-packages (from wxPython) (1.11.0)
twisted 18.7.0 requires PyHamcrest>=1.9.0, which is not installed.
Installing collected packages: PyPubSub, wxPython
Successfully installed PyPubSub-4.0.0 wxPython-4.0.3
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

Changed the PmagPy.txt file to have the successful Python output be Python 3.7. Changed the text to:
Python 3.7.0 (default, Jun 28 2018, 07:39:16) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 

Did not see this warning last time so I am putting it here in case it is something new you want to know about:
Successfully installed pmagpy-cli-4.2.1
(base) kamacite:~ test2$ python
Python 3.7.0 (default, Jun 28 2018, 07:39:16) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from pmagpy import pmag
/Users/test2/anaconda3/lib/python3.7/site-packages/matplotlib/font_manager.py:281: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  'Matplotlib is building the font cache using fc-list.

Since basemap is no longer mentioned in the main cookbook and not installed, I think the lines:
Installing the Etopo20 package for use with Basemap:

install_etopo.py

Should be removed from the OSX pip install page. Not sure, so I did not remove it myself. 
I did not recompile the .tex files.

No show stoppers here, so I think we are ready to release. Not sure if you want to update to cookbook before I send out a notice (which I'll send around first)

**Comment by njarboe** [comment]
@moonshoes87 Not sure if I needed to @ you so you will get a message about this issue so adding that here.

**Comment by moonshoes87** [comment]
Thanks for looking this over, @njarboe.  Your updates look good.  

I will:

- Add instructions to ignore pip dependency warnings 
- Remove the 'install\_etopo' section from the install instructions
- Add in a small section somewhere about Basemap and how to continue using it if desired
- Probably add `pip install --upgrade pip setuptools` to install instructions (need to also check and see if `conda upgrade pip` works

I have a few clarifying questions for the remaining points.  

- What did you have in mind about adding links to section 1.2 for developer/pip install?  There are already links to each set of install instructions, but maybe I am not understanding what you are looking for.
- I have seen the matplotlib warning before.  Do you think we should add it to the Cookbook somewhere?

**Comment by njarboe** [comment]
You have a link to standalone programs so I was looking for one for the pip install. I made changes to PmagPy.tex to what I think would be better but am not sure if:

\item You can use pip to download and install the {\bf PmagPy} function library and the \href{#full_install}{{\bf PmagPy} command line} programs. 

Will compile. All these {/bf PmagPy} that don't seem to boldface in the online formatted version

I don't think you need to add any thing about the matplotlib warning.

**Comment by moonshoes87** [comment]
Ah, I see what you're saying.  I'll make sure that link is there and working.

I don't want to rename the section to pip/developer install (since lots of people won't know what either of those things mean), but if you think of something more clear then let me know.  

I'll work on fixing all those pieces tonight or tomorrow.

**Comment by moonshoes87** [comment]
I've published everything except the basemap section and adding `pip install --upgrade pip setuptools`.  Will add those tomorrow.

**Comment by moonshoes87** [comment]
Ok, I've made a last few changes to the install instructions.  I've added a Basemap section under Troubleshooting.  I think it is good to go.
