### ISSUE TITLE
gh-pages as the default branch

### ISSUE THREAD

**Issue by Swanson-Hysell** [PmagPy/PmagPy-Cookbook#3]
I was talking to someone here at Berkeley with more Github experience than I and he suggested that to resolve the problem with differences between the master and gh-pages we could set the default branch to be gh-pages. I don't have permissions to do this...but it looks like it can be done in Settings by the repository owner. Then the master branch could simply be deleted (there is nothing special about the master branch other than its name) and a repo can simply have a single gh-pages branch.

The only issue I can see with deleting the master is that the Datafiles folder wouldn't be hosted in this repository, but maybe that is ok. Perhaps it could be in the main PmagPy repo? Alternatively, we could keep the master branch, but have the only thing in there be the Datafiles folder as I gather that two branches don't actually have to have the same content.

**Comment by rminnett** [comment]
From the README.md, it looks like Lisa was using the master branch as a staging branch. You have the authority to change the default branch now if to want to do this. Just double check that master isn't ahead of gh-pages before deleting it, though.

**Comment by rminnett** [comment]
I made the gh-pages branch the default and Nick deleted the master branch.
