### ISSUE TITLE
update links to programs (docs) to include programs folder reorganization

### ISSUE THREAD

**Issue by Swanson-Hysell** [PmagPy/PmagPy-Cookbook#6]
Links like this one are broken in the cookbook:

https://github.com/ltauxe/PmagPy/blob/master/find_EI.py

This link appropriately points to 

https://github.com/ltauxe/PmagPy/blob/master/find_EI.py

but should point to:

https://github.com/PmagPy/PmagPy/blob/master/programs/find_EI.py

**Comment by ltauxe** [comment]
I’m fixing all of these to follow the form: 
> https://github.com/PmagPy/PmagPy/blob/master/programs/find_EI.py <https://github.com/PmagPy/PmagPy/blob/master/programs/find_EI.py>
>

**Comment by ltauxe** [comment]
I did this - BUT - i think the GUI documentation is messed up.  because those are not in programs.  and I’m missing the thellier_gui.pdf

where should this go?  and where is it?  

lisa

**Comment by moonshoes87** [comment]
Yes, links to the 4 GUIs should follow the format:

https://github.com/PmagPy/PmagPy/blob/master/magic_gui.py 

I don’t know about the thellier_gui.pdf.  Where was it before?

**Comment by Swanson-Hysell** [comment]
The thellier_gui pdf that @ronshaar put together is in the cookbook repo:

https://github.com/PmagPy/PmagPy-Cookbook/blob/gh-pages/thellier_GUI_full_manual_1_0.pdf

It is nice thorough documentation so it would be nice to link to.
